### ISSUE TITLE
azure configurations for Cars Island

### ISSUE THREAD

**Issue by alexandrejobin** [Daniel-Krzyczkowski/Cars-Island-On-Azure#2]
Hi!

I've read your article about the deployment of Cars Island on Azure but I don't see how you have configured, step by step, the services that you use. I'm totally new to Azure and we are beginning to evaluate the possibilitiy to migrate our web sites there are you article is very important to me but it presume that people already know Azure.

Would it be possible to put a little article to explain the steps to achive that?

thank you very much!

**Comment by Daniel-Krzyczkowski** [comment]
Hi Alex,

Thank you for reaching out to me. I am glad that you found my project helpful and valuable.
When it comes to step by step configuration - I did not plan to publish such content. I have also many other requests around this project. This is why I enabled sponsorship for this project and my profile. I would like to help everyone but in this case I need more time to provide valuable content. 
If I will have some I will try to publish explanation you mentioned. If you like the project you can also support this project as a sponsor:
https://github.com/Daniel-Krzyczkowski/Cars-Island-On-Azure

Once again thank you for a kind words!

**Comment by alexandrejobin** [comment]
I've just found that you have the ARM templates. I tried it but got difficulties with KeyVault et SendGrid so I had to remove them from the template. SendGrid doesn't have the free 25k anymore!

Thank you for your work!

**Comment by Daniel-Krzyczkowski** [comment]
When it comes to SendGrid - I noticed too that free tier disappeared in the Azure portal. However I was manage to create SendGrid service with free tier using ARM templates.

To create Azure SendGrid service, terms and conditions has to be accepted for the Azure subscription first. To do it below Azure CLI script can be used:

```
az account set --subscription <<subscription ID>>

az vm image accept-terms --publisher sendgrid --offer sendgrid_azure --plan free
```

After executing the script, there will be below information displayed. It is important to check if new command is available:

This command has been deprecated and will be removed in version '3.0.0'. Use 'az vm image terms accept' instead.
