### ISSUE TITLE
Token request status returned 404

### ISSUE THREAD

**Issue by justoke** [Daniel-Krzyczkowski/Cars-Island-On-Azure#4]
Hi Daniel,

Awesome collection of articles and a ton of useful information. I'm struggling with the article steps https://daniel-krzyczkowski.github.io/Cars-Island-ASP-NET-Core-API-Secured-By-Azure-AD-B2C/ , in particular the request for the token.

The part that is somewhat vague is where does the policy name come from and in particular where  is this configured in the Azure AD B2C? I see that in the config you have policy name set to B2C_1A_SignUpOrSignin, and the token request would be constructed as follows (I used the docs to check the format https://docs.microsoft.com/en-gb/azure/active-directory-b2c/access-tokens) 
https://<tenant>.b2clogin.com/<tenant>.onmicrosoft.com/<PolicyName>/oauth2/v2.0/authorize?client_id=xxxx etc

I get an http 404 as I have not configured a policy and nor do I see where to do this. I looked at the docs https://docs.microsoft.com/en-gb/azure/active-directory-b2c/user-flow-overview and the refer to User flows and Custom policy but I do not see the User flows menu anywhere on the Azure AD B2C configuration. 

Thank you.

**Comment by Daniel-Krzyczkowski** [comment]
Hi,

Thank you for letting me know, I am happy that you found my articles interesting and helpful.
When it comes to your question.
In the Cars Island project I used custom policies (Identity Experience Framework) in the Azure AD B2C.
Below two links can help you understand the concept behind custom policies and how to setup them:

[Azure AD B2C custom policy overview](https://docs.microsoft.com/en-us/azure/active-directory-b2c/custom-policy-overview)

[Tutorial: Create user flows in Azure Active Directory B2C](https://docs.microsoft.com/en-us/azure/active-directory-b2c/tutorial-create-user-flows?pivots=b2c-custom-policy)

This is the screenshot from my Azure AD B2C tenant created for Cars Island project:

![sc1](https://user-images.githubusercontent.com/15244422/118270828-d4b0a900-b4c0-11eb-884c-734595c5004f.PNG)

![sc2](https://user-images.githubusercontent.com/15244422/118270839-d7ab9980-b4c0-11eb-86c4-27511ce71df1.PNG)

I hope above details will help you.

**Comment by justoke** [comment]
Thank you for the details - I managed to find the User flows - Azure AD and Azure AD B2C have their own configuration as I now know. I should be able to find my way further.

Are you perhaps available for some consulting work?

**Comment by Daniel-Krzyczkowski** [comment]
Great to know. Yes, I am available so please let me know once you need additional help.

**Comment by justoke** [comment]
I've managed to create the app registrations and used the built-in user flows for now as I don't need the customization policies just yet. I have tried to run the API and web app locally. Figured out how to Authorize the web api, set up local Cosmosdb emulator and tried to run the web app, but when I click login I get this. Any idea what this might be?

![image](https://user-images.githubusercontent.com/26506785/118543427-2a4cb600-b74c-11eb-8ad8-14f62d6ff84f.png)

**Comment by justoke** [comment]
I managed to figure it out and get the token. There are some inconsistencies in the documentation versus the actual query string format. I copied the URL from the Run user flow and compared to the docs and figured it out from there.

Please let me know how to contact you as I am looking for some consultancy on a project.
