### ISSUE TITLE
Typo in your article

### ISSUE THREAD

**Issue by damienaicheh** [Daniel-Krzyczkowski/Cars-Island-On-Azure#9]
Hi Daniel, 

Just to tell you that I found a little typo in your article: https://daniel-krzyczkowski.github.io/Cars-Island-ASP-NET-Core-API-Integration-With-Azure-Cosmos-DB/
Just on top of the `CarRepository` the link is not displayed correctly.

Have a nice day!

Damien

**Comment by Daniel-Krzyczkowski** [comment]
Thank you!
